import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Qr Code Generator App",
   description: "Generated by Nurullah Nergiz",
   keywords: "qrcode, nurullah,Nurullah Nergiz,",
   // meta:,
   robots: "index",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <head>
            <link
               href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
               rel="stylesheet"></link>
         </head>
         <body className={inter.className}>
            <section className="container h-16 p-4 mx-auto flex items-center justify-between bg-white rounded-md shadow-md shadow-gray-500">
               <header className="w">Logo</header>
               <nav className="w">
                  <Link href="/" className="bx bx-home text-2xl">
                     Home
                  </Link>
               </nav>
            </section>
            <main className="container h-full p-4 mx-auto my-4 bg-white rounded-md shadow-md shadow-gray-500">
               {children}
            </main>
            <footer className="container h-16 p-4 mx-auto bg-white rounded-md shadow-md shadow-gray-500">
               asd
            </footer>
         </body>
      </html>
   );
}
